---

# Bring stack down

- hosts: machine1
  become: true
  tasks:
    - service: name=nginx state=stopped
    - wait_for: port=80 state=drained

- hosts: machine2
  become: true
  tasks:
    - service: name=apache2 state=stopped
    - wait_for: port=80 state=stopped

- hosts: machine3
  become: true
  tasks:
    - service: name=mysql state=restarted
    - wait_for: port=3306 state=stopped
