---

# Bring stack down

- hosts: machine1
  become: true
  tasks:
    - service: name=nginx state=stopped

- hosts: machine2
  become: true
  tasks:
    - service: name=apache2 state=stopped

- hosts: machine3
  become: true
  tasks:
    - service: name=mysql state=stopped

# Bring stack up

- hosts: machine1
  become: true
  tasks:
    - service: name=nginx state=started

- hosts: machine2
  become: true
  tasks:
    - service: name=apache2 state=started

- hosts: machine3
  become: true
  tasks:
    - service: name=mysql state=started
